# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: procmon.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'procmon.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rprocmon.proto\x12\x07procmon\"\x0f\n\rStatusRequest\"\xbe\x01\n\x0eStatusResponse\x12\x11\n\tcpu_usage\x18\x01 \x01(\x01\x12\x11\n\tmem_usage\x18\x02 \x01(\x01\x12\x14\n\x0ctotal_memory\x18\x03 \x01(\x01\x12\x13\n\x0b\x66ree_memory\x18\x04 \x01(\x01\x12\x15\n\rnet_interface\x18\x05 \x01(\t\x12\x10\n\x08rx_bytes\x18\x06 \x01(\x03\x12\x10\n\x08tx_bytes\x18\x07 \x01(\x03\x12\x0f\n\x07\x64_speed\x18\x08 \x01(\x01\x12\x0f\n\x07u_speed\x18\t \x01(\x01\"\x13\n\x11NftTrafficRequest\">\n\x12NftTrafficResponse\x12(\n\x0bnft_traffic\x18\x01 \x03(\x0b\x32\x13.procmon.NftTraffic\"h\n\nNftTraffic\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x12\n\nip_address\x18\x02 \x01(\t\x12\x13\n\x0bmac_address\x18\x03 \x01(\t\x12\x0f\n\x07packets\x18\x04 \x01(\x05\x12\r\n\x05\x62ytes\x18\x05 \x01(\x05\x32\x9e\x01\n\x0eProcmonService\x12\x42\n\x0fGetSystemStatus\x12\x16.procmon.StatusRequest\x1a\x17.procmon.StatusResponse\x12H\n\rGetNftTraffic\x12\x1a.procmon.NftTrafficRequest\x1a\x1b.procmon.NftTrafficResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'procmon_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUSREQUEST']._serialized_start=26
  _globals['_STATUSREQUEST']._serialized_end=41
  _globals['_STATUSRESPONSE']._serialized_start=44
  _globals['_STATUSRESPONSE']._serialized_end=234
  _globals['_NFTTRAFFICREQUEST']._serialized_start=236
  _globals['_NFTTRAFFICREQUEST']._serialized_end=255
  _globals['_NFTTRAFFICRESPONSE']._serialized_start=257
  _globals['_NFTTRAFFICRESPONSE']._serialized_end=319
  _globals['_NFTTRAFFIC']._serialized_start=321
  _globals['_NFTTRAFFIC']._serialized_end=425
  _globals['_PROCMONSERVICE']._serialized_start=428
  _globals['_PROCMONSERVICE']._serialized_end=586
# @@protoc_insertion_point(module_scope)
