// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: procmon.proto
#ifndef GRPC_procmon_2eproto__INCLUDED
#define GRPC_procmon_2eproto__INCLUDED

#include "procmon.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace procmon {

class ProcmonService final {
 public:
  static constexpr char const* service_full_name() {
    return "procmon.ProcmonService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetSystemStatus(::grpc::ClientContext* context, const ::procmon::StatusRequest& request, ::procmon::StatusResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::procmon::StatusResponse>> AsyncGetSystemStatus(::grpc::ClientContext* context, const ::procmon::StatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::procmon::StatusResponse>>(AsyncGetSystemStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::procmon::StatusResponse>> PrepareAsyncGetSystemStatus(::grpc::ClientContext* context, const ::procmon::StatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::procmon::StatusResponse>>(PrepareAsyncGetSystemStatusRaw(context, request, cq));
    }
    virtual ::grpc::Status GetNftTraffic(::grpc::ClientContext* context, const ::procmon::NftTrafficRequest& request, ::procmon::NftTrafficResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::procmon::NftTrafficResponse>> AsyncGetNftTraffic(::grpc::ClientContext* context, const ::procmon::NftTrafficRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::procmon::NftTrafficResponse>>(AsyncGetNftTrafficRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::procmon::NftTrafficResponse>> PrepareAsyncGetNftTraffic(::grpc::ClientContext* context, const ::procmon::NftTrafficRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::procmon::NftTrafficResponse>>(PrepareAsyncGetNftTrafficRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetSystemStatus(::grpc::ClientContext* context, const ::procmon::StatusRequest* request, ::procmon::StatusResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetSystemStatus(::grpc::ClientContext* context, const ::procmon::StatusRequest* request, ::procmon::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetNftTraffic(::grpc::ClientContext* context, const ::procmon::NftTrafficRequest* request, ::procmon::NftTrafficResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetNftTraffic(::grpc::ClientContext* context, const ::procmon::NftTrafficRequest* request, ::procmon::NftTrafficResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::procmon::StatusResponse>* AsyncGetSystemStatusRaw(::grpc::ClientContext* context, const ::procmon::StatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::procmon::StatusResponse>* PrepareAsyncGetSystemStatusRaw(::grpc::ClientContext* context, const ::procmon::StatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::procmon::NftTrafficResponse>* AsyncGetNftTrafficRaw(::grpc::ClientContext* context, const ::procmon::NftTrafficRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::procmon::NftTrafficResponse>* PrepareAsyncGetNftTrafficRaw(::grpc::ClientContext* context, const ::procmon::NftTrafficRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetSystemStatus(::grpc::ClientContext* context, const ::procmon::StatusRequest& request, ::procmon::StatusResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::procmon::StatusResponse>> AsyncGetSystemStatus(::grpc::ClientContext* context, const ::procmon::StatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::procmon::StatusResponse>>(AsyncGetSystemStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::procmon::StatusResponse>> PrepareAsyncGetSystemStatus(::grpc::ClientContext* context, const ::procmon::StatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::procmon::StatusResponse>>(PrepareAsyncGetSystemStatusRaw(context, request, cq));
    }
    ::grpc::Status GetNftTraffic(::grpc::ClientContext* context, const ::procmon::NftTrafficRequest& request, ::procmon::NftTrafficResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::procmon::NftTrafficResponse>> AsyncGetNftTraffic(::grpc::ClientContext* context, const ::procmon::NftTrafficRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::procmon::NftTrafficResponse>>(AsyncGetNftTrafficRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::procmon::NftTrafficResponse>> PrepareAsyncGetNftTraffic(::grpc::ClientContext* context, const ::procmon::NftTrafficRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::procmon::NftTrafficResponse>>(PrepareAsyncGetNftTrafficRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetSystemStatus(::grpc::ClientContext* context, const ::procmon::StatusRequest* request, ::procmon::StatusResponse* response, std::function<void(::grpc::Status)>) override;
      void GetSystemStatus(::grpc::ClientContext* context, const ::procmon::StatusRequest* request, ::procmon::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetNftTraffic(::grpc::ClientContext* context, const ::procmon::NftTrafficRequest* request, ::procmon::NftTrafficResponse* response, std::function<void(::grpc::Status)>) override;
      void GetNftTraffic(::grpc::ClientContext* context, const ::procmon::NftTrafficRequest* request, ::procmon::NftTrafficResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::procmon::StatusResponse>* AsyncGetSystemStatusRaw(::grpc::ClientContext* context, const ::procmon::StatusRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::procmon::StatusResponse>* PrepareAsyncGetSystemStatusRaw(::grpc::ClientContext* context, const ::procmon::StatusRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::procmon::NftTrafficResponse>* AsyncGetNftTrafficRaw(::grpc::ClientContext* context, const ::procmon::NftTrafficRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::procmon::NftTrafficResponse>* PrepareAsyncGetNftTrafficRaw(::grpc::ClientContext* context, const ::procmon::NftTrafficRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetSystemStatus_;
    const ::grpc::internal::RpcMethod rpcmethod_GetNftTraffic_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetSystemStatus(::grpc::ServerContext* context, const ::procmon::StatusRequest* request, ::procmon::StatusResponse* response);
    virtual ::grpc::Status GetNftTraffic(::grpc::ServerContext* context, const ::procmon::NftTrafficRequest* request, ::procmon::NftTrafficResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetSystemStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetSystemStatus() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetSystemStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSystemStatus(::grpc::ServerContext* /*context*/, const ::procmon::StatusRequest* /*request*/, ::procmon::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetSystemStatus(::grpc::ServerContext* context, ::procmon::StatusRequest* request, ::grpc::ServerAsyncResponseWriter< ::procmon::StatusResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetNftTraffic : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetNftTraffic() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetNftTraffic() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNftTraffic(::grpc::ServerContext* /*context*/, const ::procmon::NftTrafficRequest* /*request*/, ::procmon::NftTrafficResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetNftTraffic(::grpc::ServerContext* context, ::procmon::NftTrafficRequest* request, ::grpc::ServerAsyncResponseWriter< ::procmon::NftTrafficResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetSystemStatus<WithAsyncMethod_GetNftTraffic<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetSystemStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetSystemStatus() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::procmon::StatusRequest, ::procmon::StatusResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::procmon::StatusRequest* request, ::procmon::StatusResponse* response) { return this->GetSystemStatus(context, request, response); }));}
    void SetMessageAllocatorFor_GetSystemStatus(
        ::grpc::MessageAllocator< ::procmon::StatusRequest, ::procmon::StatusResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::procmon::StatusRequest, ::procmon::StatusResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetSystemStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSystemStatus(::grpc::ServerContext* /*context*/, const ::procmon::StatusRequest* /*request*/, ::procmon::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetSystemStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::procmon::StatusRequest* /*request*/, ::procmon::StatusResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetNftTraffic : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetNftTraffic() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::procmon::NftTrafficRequest, ::procmon::NftTrafficResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::procmon::NftTrafficRequest* request, ::procmon::NftTrafficResponse* response) { return this->GetNftTraffic(context, request, response); }));}
    void SetMessageAllocatorFor_GetNftTraffic(
        ::grpc::MessageAllocator< ::procmon::NftTrafficRequest, ::procmon::NftTrafficResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::procmon::NftTrafficRequest, ::procmon::NftTrafficResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetNftTraffic() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNftTraffic(::grpc::ServerContext* /*context*/, const ::procmon::NftTrafficRequest* /*request*/, ::procmon::NftTrafficResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetNftTraffic(
      ::grpc::CallbackServerContext* /*context*/, const ::procmon::NftTrafficRequest* /*request*/, ::procmon::NftTrafficResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetSystemStatus<WithCallbackMethod_GetNftTraffic<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetSystemStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetSystemStatus() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetSystemStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSystemStatus(::grpc::ServerContext* /*context*/, const ::procmon::StatusRequest* /*request*/, ::procmon::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetNftTraffic : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetNftTraffic() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetNftTraffic() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNftTraffic(::grpc::ServerContext* /*context*/, const ::procmon::NftTrafficRequest* /*request*/, ::procmon::NftTrafficResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetSystemStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetSystemStatus() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetSystemStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSystemStatus(::grpc::ServerContext* /*context*/, const ::procmon::StatusRequest* /*request*/, ::procmon::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetSystemStatus(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetNftTraffic : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetNftTraffic() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetNftTraffic() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNftTraffic(::grpc::ServerContext* /*context*/, const ::procmon::NftTrafficRequest* /*request*/, ::procmon::NftTrafficResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetNftTraffic(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetSystemStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetSystemStatus() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetSystemStatus(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetSystemStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSystemStatus(::grpc::ServerContext* /*context*/, const ::procmon::StatusRequest* /*request*/, ::procmon::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetSystemStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetNftTraffic : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetNftTraffic() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetNftTraffic(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetNftTraffic() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNftTraffic(::grpc::ServerContext* /*context*/, const ::procmon::NftTrafficRequest* /*request*/, ::procmon::NftTrafficResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetNftTraffic(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetSystemStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetSystemStatus() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::procmon::StatusRequest, ::procmon::StatusResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::procmon::StatusRequest, ::procmon::StatusResponse>* streamer) {
                       return this->StreamedGetSystemStatus(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetSystemStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetSystemStatus(::grpc::ServerContext* /*context*/, const ::procmon::StatusRequest* /*request*/, ::procmon::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetSystemStatus(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::procmon::StatusRequest,::procmon::StatusResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetNftTraffic : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetNftTraffic() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::procmon::NftTrafficRequest, ::procmon::NftTrafficResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::procmon::NftTrafficRequest, ::procmon::NftTrafficResponse>* streamer) {
                       return this->StreamedGetNftTraffic(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetNftTraffic() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetNftTraffic(::grpc::ServerContext* /*context*/, const ::procmon::NftTrafficRequest* /*request*/, ::procmon::NftTrafficResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetNftTraffic(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::procmon::NftTrafficRequest,::procmon::NftTrafficResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetSystemStatus<WithStreamedUnaryMethod_GetNftTraffic<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetSystemStatus<WithStreamedUnaryMethod_GetNftTraffic<Service > > StreamedService;
};

}  // namespace procmon


#endif  // GRPC_procmon_2eproto__INCLUDED
